# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'SUB-wmslab(1)(f1172213-e651-43f1-876e-a00ad8959726)'
    ScriptType: 'InlineScript'
    Inline: |
      Connect-AzAccount
      New-AzSubscriptionDeployment -Name AzureLighthouse `
                       -Location Westus 2 `
                       -TemplateUri https://raw.githubusercontent.com/mspanil/Lighthouse-demo/main/create_web_app/Cybershield1.json?token=GHSAT0AAAAAACNUOVTLNGZPUI5JFRQHSQYKZN4YZWQ `
                       -Verbose
    azurePowerShellVersion: 'LatestVersion'
    workingDirectory: 'c:\'