openapi: 3.0.1
info:
  title: Get SecureScore from Microsoft Graph API
  description: Get Secure score from Graph API.
  version: 'v1'
servers:
  - url: https://management.azure.com/subscriptions/f1172213-e651-43f1-876e-a00ad8959726/providers/Microsoft.Security/secureScores/ascScore?api-version=2020-01-01
paths:
    /providers/Microsoft.Security/secureScores/ascScore?api-version=2020-01-01:
    get:
      operationId: getsecurescore
      summary: Get Secure score.
      parameters:
      - in: path
        name: ascScore
        schema:
            type: string
        required: true
        description: Get Secure secure.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '/providers/Microsoft.Security/secureScores/ascScore?api-version=2020-01-01'

components:
  schemas:
    getSecurescore:
      type: object
      properties:
        todos:
          type: array
          items:
            type: string
          description: The list of securescore.
