openapi: "3.0.0"
info:
  title: Microsoft Graph API
  description: Configuration for accessing Microsoft Graph API
  version: 1.0.0
servers:
  - url: https://graph.microsoft.com/v1.0
paths:
  /me:
    get:
      summary: Get current user details
      operationId: getCurrentUser
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The user's ID
                  displayName:
                    type: string
                    description: The user's display name
                  email:
                    type: string
                    description: The user's email address
                required:
                  - id
                  - displayName
                  - email
      security:
        - oauth2:
            - openid
            - profile
            - email
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://login.microsoftonline.com/your-tenant-id/oauth2/v2.0/authorize
          tokenUrl: https://login.microsoftonline.com/your-tenant-id/oauth2/v2.0/token
          scopes:
            openid: Sign in and read user profile
            profile: Read user profile
            email: Read user email
