openapi: 3.0.1
info:
  title: Microsoft Graph for SecureScore
  description: Get secure score for tenant. Show all available Secure score value.
  version: 'v1'

servers:
- url: https://management.azure.com/subscriptions/f1172213-e651-43f1-876e-a00ad8959726/providers/Microsoft.Security/secureScores/{secureScoreName}?api-version=2020-01-01
paths:
  "/Microsoft.Security/secureScores/{secureScoreName}?api-version=2020-01-01":
    get:
      summary: Get tenant security secureScores
      operationId: Get.v1.0.security.secureScores
      parameters:
      - name: "{id}"
        in: query
        schema:
          type: string
      - name: sec-ch-ua-platform-version
        in: header
        schema:
          type: string
      - name: X-Edge-Shopping-Flag
        in: header
        schema:
          type: string
      responses:
         "200":
          description: OK
         '401':
          description: Unauthorized
          headers:
            request-id:
              schema:
                type: string
            client-request-id:
              schema:
                type: string
            x-ms-ags-diagnostic:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                      message:
                        type: string
                      innerError:
                        type: object
                        properties:
                          date:
                            type: string
                          request-id:
                            type: string
                          client-request-id:
                            type: string
x-ms-generated-by:
  toolName: Dev Proxy
  toolVersion: 0.14.1
