openapi: 3.0.0
info:
  title: Secure Scores API
  version: 1.0.0
servers:
  - url: https://graph.microsoft.com
paths:
  /v1.0/security/secureScores:
    get:
      summary: Get secure scores for cloud resources
      responses:
        '200':
          description: Array of secure scores
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/secureScore'
components:
  schemas:
    secureScore:
      type: object
      properties:
        resourceId:
          type: string
        score:
          type: integer
        category:
          type: string
        description:
          type: string
        lastUpdated:
          type: string
          format: date-time
