openapi: 3.0.0

info:
  title: Shodan REST API Documentation
  version: "1.0.0"

servers:
  - url: https://api.shodan.io

Components:
   securitySchemes:
     ApikeyAuth:
       type: apikey
       in: query
       name: key

tags:
  - name: Search Methods
    description: Endpoints related to searching on shodan

paths:
    /shodan/host/{ip}:
      get:
        tags:
          - Search Methods
        security:
          - ApikeyAuth: []
        parametes:
          - in: query
            name: history
            schema:
              type: boolean
          - in: query
            name: mimify
            schema:
              type: boolean
          - in: path
            name: ip
            required: true
            schema:
              type: string
        responses:
          '200':
             description: Success
          '400':
             description: Bad Request
          '500':
             description: Internal Server Error

          
